/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20MockSol from "./ERC20MOCK.sol";
export type { erc20MockSol };
export type { MarsxCommunity } from "./MarsxCommunity";
