/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20MockSol from "./ERC20MOCK.sol";
export { MarsxCommunity__factory } from "./MarsxCommunity__factory";
